name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "${{matrix.cfg.name}}"
    runs-on: "${{matrix.cfg.os}}"
    strategy:
      fail-fast: false
      matrix:
        cfg:
          # gcc 11/12
          - name: "ubuntu gcc 15 Debug"
            os: ubuntu-26.04
            build_type: Debug
            cc: gcc-15
            cxx: g++-15
            codecov: true
          - name: "ubuntu gcc 15 Release"
            os: ubuntu-26.04
            build_type: Release
            cc: gcc-15
            cxx: g++-15
          - name: "ubuntu gcc 14 Debug"
            os: ubuntu-24.04
            build_type: Debug
            cc: gcc-14
            cxx: g++-14
            codecov: true
          - name: "ubuntu gcc 14 Release"
            os: ubuntu-24.04
            build_type: Release
            cc: gcc-14
            cxx: g++-14

          # clang 21 on ubuntu
          - name: "ubuntu clang 21 Debug"
            os: ubuntu-26.04
            build_type: Debug
            cc: clang-21
            cxx: clang++-21
          - name: "ubuntu clang 21 Release"
            os: ubuntu-26.04
            build_type: Release
            cc: clang-21
            cxx: clang++-21
          - name: "ubuntu clang 21 libcxx Debug"
            os: ubuntu-26.04
            build_type: Debug
            cc: clang-21
            cxx: clang++-21
            libcxx: true
          - name: "ubuntu clang 21 libcxx Release"
            os: ubuntu-26.04
            build_type: Release
            cc: clang-21
            cxx: clang++-21
            libcxx: true

          # clang 21 on macos
          - name: "macos clang 21 Debug"
            os: macos-26
            build_type: Debug
            cc: /usr/local/opt/llvm@21/bin/clang-21
            cxx: /usr/local/opt/llvm@21/bin/clang++
          - name: "macos clang 21 Release"
            os: macos-26
            build_type: Release
            cc: /usr/local/opt/llvm@21/bin/clang-21
            cxx: /usr/local/opt/llvm@21/bin/clang++

          # apple clang 21
          - name: "macos apple clang 21 Debug"
            os: macos-26
            build_type: Debug
            cc: clang
            cxx: clang++
          - name: "macos apple clang 21 Release"
            os: macos-26
            build_type: Release
            cc: clang
            cxx: clang++


    ###################################################
    ## building steps
    ###################################################
    steps:
      - uses: actions/checkout@v7

      # init install path and llvm version tag
      - name: "init libcxx env variables"
        if: matrix.cfg.libcxx
        id: init
        shell: bash
        run: |
          llvm_tag=llvmorg-21.1.8
          echo "llmv-version=$llvm_tag" >> $GITHUB_OUTPUT
          echo "LIBCXX_INSTALL_TAG=$llvm_tag" >> $GITHUB_ENV
          echo "LIBCXX_INSTALL_PATH=`pwd`/local" >> $GITHUB_ENV

      # install clang 21 and libc++ if necessary
      - name: "install clang 21"
        if: startsWith(matrix.cfg.os, 'ubuntu') && startsWith(matrix.cfg.cxx, 'clang++')
        working-directory: "${{env.HOME}}"
        shell: bash
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21

      # cache the llvm installation
      - name: "cache llvm"
        if: matrix.cfg.libcxx
        uses: actions/cache@v6
        id: cache-llvm
        with:
          path: "${{env.LIBCXX_INSTALL_PATH}}"
          # we always build as Release, so don't make a separate cache entry for debug
          key: ${{runner.os}}-${{matrix.cfg.os}}-Release-${{steps.init.outputs.llmv-version}}

      # if not cached, actually build stuff
      - name: "checkout llvm"
        if: matrix.cfg.libcxx && steps.cache-llvm.outputs.cache-hit != 'true'
        uses: actions/checkout@v7
        with:
          repository: llvm/llvm-project
          ref: ${{env.LIBCXX_INSTALL_TAG}}
          path: llvm-project
      - name: "install llvm libc++"
        if: matrix.cfg.libcxx && steps.cache-llvm.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo source from checkout action should be here...
          ls -lh
          cd llvm-project

          echo building libcxx from source...
          cmake \
            -S runtimes \
            -B build \
            -D CMAKE_C_COMPILER=gcc-15 \
            -D CMAKE_CXX_COMPILER=g++-15 \
            -D LLVM_ENABLE_RUNTIMES='libcxx;libcxxabi;libunwind' \
            -D "CMAKE_INSTALL_PREFIX=${{env.LIBCXX_INSTALL_PATH}}" \
            -D CMAKE_BUILD_TYPE=Release
          cmake --build build --target install-cxx
          cmake --build build --target install-cxxabi

      # setup compiler for the main build steps
      - name: "setup compiler"
        shell: bash
        run: |
          echo test
          which clang++ || true
          clang++ --version || true
          echo test2
          which clang++-20 || true
          clang++-20 --version || true
          which clang++-21 || true
          clang++-21 --version || true
          echo test gcov
          which gcov || true
          gcov --version || true
          echo test end
          echo "CC=${{matrix.cfg.cc}}" >> $GITHUB_ENV
          echo "CXX=${{matrix.cfg.cxx}}" >> $GITHUB_ENV
          if [[ ${{matrix.cfg.os}} != windows-* ]]; then

            if [[ "x${{matrix.cfg.codecov}}" == "xtrue" ]]; then
              cov=" -D MKPOKER_ENABLE_CODE_COVERAGE=1"
            fi
            echo "MKP_MONO=-D CMAKE_BUILD_TYPE=${{matrix.cfg.build_type}}$cov" >> $GITHUB_ENV

            if [[ ${{matrix.cfg.os}} == ubuntu-* && "x${{matrix.cfg.libcxx}}" == "xtrue" ]]; then
              echo "CXX_ARGS=-D \"CMAKE_CXX_FLAGS=-stdlib=libc++ -nostdinc++ -cxx-isystem ${{env.LIBCXX_INSTALL_PATH}}/include/c++/v1 -Wno-unused-command-line-argument\"" >> $GITHUB_ENV
              echo "LDD_ARGS=-D \"CMAKE_EXE_LINKER_FLAGS=-L ${{env.LIBCXX_INSTALL_PATH}}/lib -Wl,-rpath,${{env.LIBCXX_INSTALL_PATH}}/lib -lc++abi\"" >> $GITHUB_ENV
            elif [[ ${{matrix.cfg.os}} == macos-* && "x${{matrix.cfg.cc}}" == "/usr/local/opt/llvm@21/bin/clang-21" ]]; then
              echo "CXX_ARGS=-D \"CMAKE_CXX_FLAGS=-stdlib=libc++ -nostdinc++ -cxx-isystem /usr/local/opt/llvm@21/include/c++/v1\"" >> $GITHUB_ENV
              echo "LDD_ARGS=-D \"CMAKE_EXE_LINKER_FLAGS=-L /usr/local/opt/llvm@21/lib -Wl,-rpath,/usr/local/opt/llvm@21/lib -lc++abi\"" >> $GITHUB_ENV
            fi

          else
            echo "MKP_MULTI=--config ${{matrix.cfg.build_type}}" >> $GITHUB_ENV
          fi

      # at the moment non-msvc builds are 'mono config' and need the build_type set during config
      - name: configure
        shell: bash
        run: |
          cmake \
          -S . \
          -B build \
          -D MKPOKER_BUILD_TESTS=ON -D MKPOKER_BUILD_EXAMPLES=ON -D MKPOKER_BUILD_FOR_DEV=ON \
          ${{env.CXX_ARGS}} \
          ${{env.LDD_ARGS}} \
          ${{env.MKP_MONO}}

      # msvc is 'multi config' so we pass --config $build_type as arg here
      - name: build
        shell: bash
        run: |
          cmake \
          --build build \
          ${{env.MKP_MULTI}} \
          -j1 -v

      # run tests with very verbose output
      - name: run tests
        shell: bash
        run: |
          cd build
          ctest -VV

      # code coverage is only available with gcc debug
      - name: code coverage
        if: matrix.cfg.codecov
        shell: bash
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: "bash <(curl -s https://codecov.io/bash) -x gcov-15"
