name: CI

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs: 
  build: 
    name: "${{matrix.cfg.name}}"
    runs-on: "${{matrix.cfg.os}}"
    strategy: 
      fail-fast: false
      matrix: 
        cfg:
          # gcc 11/12
          - 
            name: "ubuntu gcc 11 Debug"
            os: ubuntu-22.04
            build_type: Debug
            cc: gcc-11
            cxx: g++-11
            codecov: true
          - 
            name: "ubuntu gcc 11 Release"
            os: ubuntu-22.04
            build_type: Release
            cc: gcc-11
            cxx: g++-11
          - 
            name: "ubuntu gcc 12 Debug"
            os: ubuntu-22.04
            build_type: Debug
            cc: gcc-12
            cxx: g++-12
            codecov: true
          - 
            name: "ubuntu gcc 12 Release"
            os: ubuntu-22.04
            build_type: Release
            cc: gcc-12
            cxx: g++-12

          # clang 15 on ubuntu
          - 
            name: "ubuntu clang 15 Debug"
            os: ubuntu-22.04
            build_type: Debug
            cc: clang-15
            cxx: clang++-15
          - 
            name: "ubuntu clang 15 Release"
            os: ubuntu-22.04
            build_type: Release
            cc: clang-15
            cxx: clang++-15
          - 
            name: "ubuntu clang 15 libcxx Debug"
            os: ubuntu-22.04
            build_type: Debug
            cc: clang-15
            cxx: clang++-15
            libcxx: true
          - 
            name: "ubuntu clang 15 libcxx Release"
            os: ubuntu-22.04
            build_type: Release
            cc: clang-15
            cxx: clang++-15
            libcxx: true

          # clang 14 on macos
          - 
            name: "macos clang 14 Debug"
            os: macos-12
            build_type: Debug
            cc: /usr/local/opt/llvm@14/bin/clang-14
            cxx: /usr/local/opt/llvm@14/bin/clang++
          - 
            name: "macos clang 14 Release"
            os: macos-12
            build_type: Release
            cc: /usr/local/opt/llvm@14/bin/clang-14
            cxx: /usr/local/opt/llvm@14/bin/clang++

          # apple clang 14
          - 
            name: "macos apple clang 14 Debug"
            os: macos-12
            build_type: Debug
            cc: clang
            cxx: clang++
          - 
            name: "macos apple clang 14 Release"
            os: macos-12
            build_type: Release
            cc: clang
            cxx: clang++

          # msvc
          - 
            name: "windows msvc 2019 Debug"
            os: windows-2019
            build_type: Debug
            cc: cl
            cxx: cl
          - 
            name: "windows msvc 2019 Release"
            os: windows-2019
            build_type: Release
            cc: cl
            cxx: cl
          - 
            name: "windows msvc 2022 Debug"
            os: windows-2022
            build_type: Debug
            cc: cl
            cxx: cl
          - 
            name: "windows msvc 2022 Release"
            os: windows-2022
            build_type: Release
            cc: cl
            cxx: cl

    ###################################################
    ## building steps
    ###################################################
    steps: 
      - 
        uses: actions/checkout@v3

      # init install path and llvm version tag
      -
        name: "init libcxx env variables"
        if: matrix.cfg.libcxx
        id: init
        shell: bash
        run: |
          llvm_tag=llvmorg-15.0.6
          echo "llmv-version=$llvm_tag" >> $GITHUB_OUTPUT
          echo "LIBCXX_INSTALL_TAG=$llvm_tag" >> $GITHUB_ENV
          echo "LIBCXX_INSTALL_PATH=`pwd`/local" >> $GITHUB_ENV

      # install clang 15 and libc++ if necessary
      - 
        name: "install clang 15"
        if: startsWith(matrix.cfg.os, 'ubuntu') && (matrix.cfg.cxx == 'clang++-15')
        working-directory: "${{env.HOME}}"
        shell: bash
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15

      # cache the llvm installation
      -
        name: "cache llvm"
        if: matrix.cfg.libcxx
        uses: actions/cache@v3
        id: cache-llvm
        with:
          path: "${{env.LIBCXX_INSTALL_PATH}}"
          # we always build as Release, so don't make a separate cache entry for debug
          key: ${{runner.os}}-${{matrix.cfg.os}}-Release-${{steps.init.outputs.llmv-version}}

      # if not cached, actually build stuff
      -
        name: "checkout llvm"
        if: matrix.cfg.libcxx && steps.cache-llvm.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          ref: ${{env.LIBCXX_INSTALL_TAG}}
          path: llvm-project
      - 
        name: "install llvm libc++"
        if: matrix.cfg.libcxx && steps.cache-llvm.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo source from checkout action should be here...
          ls -lh
          cd llvm-project

          echo building libcxx from source...
          cmake \
            -S runtimes \
            -B build \
            -D CMAKE_C_COMPILER=gcc-12 \
            -D CMAKE_CXX_COMPILER=g++-12 \
            -D LLVM_ENABLE_RUNTIMES='libcxx;libcxxabi' \
            -D "CMAKE_INSTALL_PREFIX=${{env.LIBCXX_INSTALL_PATH}}" \
            -D CMAKE_BUILD_TYPE=Release
          cmake --build build --target install-cxx
          cmake --build build --target install-cxxabi

      # setup compiler for the main build steps
      -
        name: "setup compiler"
        shell: bash
        run: |
          echo "CC=${{matrix.cfg.cc}}" >> $GITHUB_ENV
          echo "CXX=${{matrix.cfg.cxx}}" >> $GITHUB_ENV
          if [[ ${{matrix.cfg.os}} != windows-* ]]; then

            if [[ "x${{matrix.cfg.codecov}}" == "xtrue" ]]; then
              cov=" -D MKPOKER_ENABLE_CODE_COVERAGE=1"
            fi
            echo "MKP_MONO=-D CMAKE_BUILD_TYPE=${{matrix.cfg.build_type}}$cov" >> $GITHUB_ENV

            if [[ ${{matrix.cfg.os}} == ubuntu-* && "x${{matrix.cfg.libcxx}}" == "xtrue" ]]; then
              echo "CXX_ARGS=-D \"CMAKE_CXX_FLAGS=-stdlib=libc++ -nostdinc++ -cxx-isystem ${{env.LIBCXX_INSTALL_PATH}}/include/c++/v1 -Wno-unused-command-line-argument\"" >> $GITHUB_ENV
              echo "LDD_ARGS=-D \"CMAKE_EXE_LINKER_FLAGS=-L ${{env.LIBCXX_INSTALL_PATH}}/lib -Wl,-rpath,${{env.LIBCXX_INSTALL_PATH}}/lib -lc++abi\"" >> $GITHUB_ENV
            elif [[ ${{matrix.cfg.os}} == macos-* ]]; then
              echo "CXX_ARGS=-D \"CMAKE_CXX_FLAGS=-stdlib=libc++ -nostdinc++ -cxx-isystem /usr/local/opt/llvm@14/include/c++/v1\"" >> $GITHUB_ENV
              echo "LDD_ARGS=-D \"CMAKE_EXE_LINKER_FLAGS=-L /usr/local/opt/llvm@14/lib -Wl,-rpath,/usr/local/opt/llvm@14/lib -lc++abi\"" >> $GITHUB_ENV
            fi

          else
            echo "MKP_MULTI=--config ${{matrix.cfg.build_type}}" >> $GITHUB_ENV
          fi

      # at the moment non-msvc builds are 'mono config' and need the build_type set during config
      - 
        name: configure
        shell: bash
        run: |
          cmake \
          -S . \
          -B build \
          -D MKPOKER_BUILD_TESTS=ON -D MKPOKER_BUILD_EXAMPLES=ON -D MKPOKER_BUILD_FOR_DEV=ON \
          ${{env.CXX_ARGS}} \
          ${{env.LDD_ARGS}} \
          ${{env.MKP_MONO}}

      # msvc is 'multi config' so we pass --config $build_type as arg here
      - 
        name: build
        shell: bash
        run: |
          cmake \
          --build build \
          ${{env.MKP_MULTI}} \
          -j1 -v

      # run tests with very verbose output
      - 
        name: run tests
        shell: bash
        run: |
          cd build
          ctest -VV

      # code coverage is only available with gcc debug
      - 
        name: code coverage
        if: matrix.cfg.codecov
        shell: bash
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: "bash <(curl -s https://codecov.io/bash) -x gcov-12"
